[INV-16] Add tax and discount row
Azher9767/Invoicing pull request #17
Opened 2024-04-18 16:40 UTC by Azher9767

add tax and discount as a row to invoice form work is in progress.

2024-04-24 10:31 UTC, ahmad19 commented on app/controllers/invoices_controller.rb
> +    @invoice.line_items.destroy_all
We do not need to manually delete the dependent records like that. Just add dependent: destroy in the model infront of association, it should do the job.

2024-04-24 10:32 UTC, ahmad19 commented on app/controllers/invoices/amount_calculations_controller.rb
> +  # 3. when user updates the unit rate of line item
Move these comments at the top

2024-04-24 10:35 UTC, ahmad19 commented on app/models/concerns/tax_and_discount_validations.rb
> +  end
```suggestion
  def tax?
    amount > 0
  end

  def discount?
    amount < 0
  end
```

2024-04-24 10:36 UTC, ahmad19 commented on app/models/invoice.rb
> +  has_many :tax_and_discount_polies, as: :tax_discountable
```suggestion
  has_many :tax_and_discount_polies, as: :tax_discountable, dependent: destroy
```

2024-04-24 10:41 UTC, ahmad19 commented on spec/services/invoice_amount_calculator_spec.rb
> +  context "for non fixe tax and discount" do
```suggestion
  context "for non fixed tax and discount" do
```

2024-04-24 10:42 UTC, ahmad19 commented on app/services/invoice_amount_calculator.rb
> +        end
Lets just not consider the `fixed` type. It is unnecessary.

2024-04-24 10:42 UTC, ahmad19 requested changes
Few suggestions

2024-04-25 05:22 UTC, ahmad19 requested changes
Have a look at the new comments

2024-04-25 05:22 UTC, ahmad19 commented on app/services/invoice_amount_calculator.rb
> +        else
What is the use of else condition here?

2024-04-25 05:22 UTC, ahmad19 commented on config/routes.rb
> +    post 'amount_calculations', to: 'amount_calculations#calculate_sub_total'
Lets rename the controller as Calculator!

2024-04-25 05:31 UTC, Azher9767 commented on app/services/invoice_amount_calculator.rb
> +        else
sir at line no 8 we verify if td_poly.tax_type == 'percentage' => false, if false i used else condition at line no 14 for 'fixed' type percentage

2024-04-25 05:45 UTC, Azher9767 commented on config/routes.rb
> +    post 'amount_calculations', to: 'amount_calculations#calculate_sub_total'
done

2024-04-25 06:11 UTC, ahmad19 commented on db/migrate/20240417055721_create_tax_and_discount_poly.rb
> +      t.timestamps
```suggestion
    create_table :tax_and_discount_polies do |t|
      t.string :name, null: false
      t.references :tax_discountable, polymorphic: true, null: false
      t.string :td_type, null: false
      t.string :tax_type, null: false
      t.decimal :amount, null: false
      t.belongs_to :invoice, foreign_key: true
      t.belongs_to :tax_and_discount, foreign_key: true

      t.timestamps
```

2024-04-25 06:12 UTC, ahmad19 commented on app/models/concerns/tax_and_discount_validations.rb
> +module TaxAndDiscountValidations
```suggestion
module TaxAndDiscountQueries
```

2024-04-25 06:13 UTC, ahmad19 commented on app/models/tax_and_discount_poly.rb
> +
```suggestion
validates :name, :td_type, :tax_type, :amount, presence: true
```

2024-04-25 06:13 UTC, ahmad19 commented on app/services/invoice_amount_calculator.rb
> +        else
We need not to consider fixed type at all. But lets skip it for now

2024-04-25 06:15 UTC, ahmad19 commented on app/controllers/invoices/amount_calculations_controller.rb
> +  class AmountCalculationsController < ApplicationController
```suggestion
  class CalculatorController < ApplicationController
```

2024-04-25 06:18 UTC, ahmad19 commented on app/controllers/invoices_controller.rb
> +    @invoice.sub_total = ::InvoiceAmountCalculator.new.calculate_sub_total(@invoice.line_items, @invoice.tax_and_discount_polies)
We dont need this as it will be handled in before_save callback.

2024-04-25 06:20 UTC, ahmad19 requested changes
Added some more suggestions

2024-04-29 08:10 UTC, ahmad19 requested changes
Take a look at the fixed td type tests

2024-04-29 08:10 UTC, ahmad19 commented on spec/services/invoice_amount_calculator_spec.rb
> +  context "for fixed tax/discount" do
We have removed fixed type. Right? Update the test as well. Also since we have removed the fixed why the test is still passing?

2024-04-29 08:16 UTC, Azher9767 commented on spec/services/invoice_amount_calculator_spec.rb
> +  context "for fixed tax/discount" do
no sir test getting fail, getting error 'unknown attribute 'tax_type' for TaxAndDiscountPoly.'

2024-04-29 12:05 UTC, ahmad19 requested changes

2024-04-29 12:05 UTC, ahmad19 commented on spec/factories/line_item.rb
> +FactoryBot.define do
Factories file names are always plurals

2024-04-29 12:05 UTC, ahmad19 commented on spec/factories/tax_and_discount_poly.rb
> +    amount { 0.0 }
Why amount is 0? Set up some actual value to it.

2024-04-29 12:06 UTC, Azher9767 commented on spec/factories/line_item.rb
> +FactoryBot.define do
ok

2024-04-29 14:49 UTC, ahmad19 approved these changes

2024-04-29 14:51 UTC, merged