creating model
Azher9767/Invoicing pull request #2
Opened 2024-03-18 14:54 UTC by Azher9767

ceate model,create button and links of models, home page on UI is complete.

2024-03-20 11:10 UTC, ahmad19 commented on app/controllers/categories_controller.rb
> +      params.require(:category).permit(:name, :user_id, :product_count, :belongs_to, :user)
We do not need user_id in the params as we are handling them at the controller level. Always make sure what params you are allowing.

2024-03-20 11:10 UTC, ahmad19 commented on app/controllers/invoices_controller.rb
> +      params.require(:invoice).permit(:user_id, :line_items_count, :name, :status, :sub_total, :note, :payment_date, :due_date)
Same thing about user_id.

2024-03-20 11:12 UTC, ahmad19 commented on app/controllers/products_controller.rb
> +    @product.category_id = params[:category_id]
Since you are selecting the category from the dropdown, you dont need to again set it here. Right ?

2024-03-20 11:12 UTC, ahmad19 commented on app/controllers/products_controller.rb
> +      params.require(:product).permit(:name, :description, :unit_rate, :category_id, :unit, :user_id)
remove user_id from here.

2024-03-20 11:12 UTC, ahmad19 commented on app/controllers/tax_and_discounts_controller.rb
> +      params.require(:tax_and_discount).permit(:name, :description, :td_type, :amount, :belongs_to, :user)
Clean this up.

2024-03-20 11:13 UTC, ahmad19 commented on app/models/admin_user.rb
> +end
Remove unnecessary spaces from this file.

2024-03-20 11:14 UTC, ahmad19 commented on app/models/category.rb
> +end
```ruby
belongs_to :user
```

2024-03-20 11:14 UTC, ahmad19 commented on app/models/product.rb
> +class Product < ApplicationRecord
```ruby
belongs_to :user
```

2024-03-20 11:14 UTC, ahmad19 commented on app/models/tax_and_discount.rb
> +class TaxAndDiscount < ApplicationRecord
```ruby
belongs_to :user
```

2024-03-20 11:17 UTC, ahmad19 reviewed
LGTM, Few changes suggested!

2024-03-20 12:40 UTC, Azher9767 commented on app/views/categories/_form.html.erb
> +  </div>
done

2024-03-20 12:42 UTC, Azher9767 commented on app/models/admin_user.rb
> +end
sir actually we need to delete this , bacuase i have changed  AdminUser to User model

2024-03-21 06:23 UTC, ahmad19 commented on app/controllers/categories_controller.rb
> +      params.require(:category).permit(:name, :product_count, :user)
Remove user as well.

2024-03-21 06:24 UTC, ahmad19 commented on app/controllers/products_controller.rb
> +    # @product.category_id = params[:category_id] --> by doing this we can also handle the category_id
Just a note, we are receiving `product_params[:category_id]`

2024-03-21 06:25 UTC, ahmad19 commented on app/controllers/tax_and_discounts_controller.rb
> +      params.require(:tax_and_discount).permit(:name, :description, :td_type, :amount, :user)
remove user from here as well.

2024-03-21 06:27 UTC, ahmad19 commented on app/views/products/_form.html.erb
> +    <%= form.select :category_id, options_for_select(Category.all.map { |category| [category.name, category.id ] }), {prompt: "select category"} %>
We need the categories of the current_user.

2024-03-21 06:28 UTC, ahmad19 requested changes
Some more changes are required.

2024-03-21 09:02 UTC, ahmad19 approved these changes

2024-03-21 09:37 UTC, merged